import { createSlice } from "@reduxjs/toolkit";

//
const initialState = {
  count: 0,
};// Initial state for the counter slice

// Creating a slice of the Redux store for the counter feature
// This slice will manage the state and actions related to the counter
const counterSlice = createSlice({
  name: "counter",
  initialState,
  reducers: {
    increment: (state,action) => {
      state.count = state.count + action.payload //state.count = state.count + 1 or 5
    },// Reducer to handle increment action
    
    decrement: (state,action) => {
      state.count = state.count - action.payload; //state.count = state.count - 1
    },// Reducer to handle decrement action
  },
});

// Exporting the actions generated by createSlice
export const { increment, decrement } = counterSlice.actions;

// Exporting the reducer to be used in the store
export default counterSlice.reducer;
